### ISSUE TITLE
CI - Building error - sys.stderr.write(f"ERROR: {exc}")

### ISSUE THREAD

**Issue by vlauciani** [INGV/shakemap4-web#71]
The CI fails with this error:
```
Setting up python3-pkg-resources (20.7.0-1) ...
Setting up python3-setuptools (20.7.0-1) ...
Setting up python3-wheel (0.29.0-1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Collecting pip
  Downloading https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-21.0.1
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_PYTHON} = true ]; then   apt-get update -yqq    && apt-get -y install python3 python3-pip python3-dev build-essential    && python3 -m pip install --upgrade pip    && python3 -m pip install --upgrade virtualenv   && python3 -m pip install python-dateutil  ;fi' returned a non-zero code: 1

```

**Comment by vlauciani** [comment]
Googling I found this:
- https://exerror.com/python-pip-broken-wiith-sys-stderr-writeferror-exc/
